/*
 * Generated by scripts/saveVersion.sh
 */
@VersionAnnotation(version="1.0", revision="b40e9064bfef7e7e4e57b2e8eacb66d9c1e0deb5", branch="master",
    user="chendongsheng5", date="Wed Feb  8 07:06:20 GMT 2017", url="git://pc-cdsyjysj5/e/github/parrot-datacollector/parrot-datacollector-common",
    srcChecksum="fbce3ae91c6a87d829709bd15d47e50a")
package com.cds.bigdata.parrot;

